subscriptions:
  prod_workloads:
    - id: 153aa06c-284d-4f9c-9b5b-7b26eb8ca301 #replace this value
      service_tier: prod
global:
  tenant_id: 4e0f7edd-dd1e-4a85-861c-b49ba7f7d250 #replace this value
  publickey: &publickey ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOLVTSR7EdUieQBpqutfbvJWquMM5PhTLNVGm/LrF9+AlPBYXRUOjLjpe+Xi/7kYqs1AAl8ygniVVtz3KW8cattPcE8+Tyd+8KZO7xcaYGEDCYt2Q9Q2Na0wWZ+7MXmUk4b7D+gC62J8+9rRyIt5bjLyIYjmPmlva/UCW/7agzSy+En0XkgfZ7iP0A8sancaAKsgK7BozU7E3l6IKykAj9eENjOkcqYBSEFJdQ2nD8kk8sUZx9N1vhJywUVUi725DGImLM7ToBhYoEf5czQcyob4IZYQd/0t/ufAJuF0rprznPNQvlZF7JhyzsupF7oQAPUtT5mBr0ZBkkeitWLEUcNP952FgD7eGHXa4gONJPO4gQcdbz67FzXqGt47JA6CHO6Z4I6gGa/MN3JLQ9cCpYsoKih5wJb6ilozJYSll/1MBk7sl6IvchqoPTSZnXQ/RK/NcWuXBPlhWx5Fxw0XiSIrkkgodnvl9S3DItx3DUtFy5mAAVedBNTX/4y/JXZaM= hsingh@DESKTOP-424H6PI #replace this value
  db_password: &common_password Fdgdfhfgj#12dgdfg #replace this value 
  locations:
    - "eastus"
    - "eastus2"
  remote_state:
    rg_name: "remotestate2024070211-rg"
    storage_account: "remotestate2024070211"
    container_name: "tfstate"
  name_prefix:
    - sampleapp
  tags:
    SolutionProvider: harinder
    Solution: sampleapp
  vaults:
    vm_secrets:
      vault_id:

  whitelisted_ips: &whitelistedips
    - "72.140.51.82"
  network: &network_config
    peering:
    hub_options:
      allow_virtual_network_access: true
      allow_forwarded_traffic: true
      allow_gateway_transit: true
      use_remote_gateways: false
    spoke_options:
      allow_virtual_network_access: true
      allow_forwarded_traffic: true
      allow_gateway_transit: false
      use_remote_gateways: true

prod_workloads:
  prd:
    name:
      - prodprimary
      - prd
    tags:
      env: prodprimary
      type: normal
    network: *network_config
    aks:
      name: 
        - aksue
      rgname: 
      admin_groups:
        - AKS_Application_Owner
      # can be reset - placeholder public SSH key
      public_ssh_key: *publickey
      admin_username: aks_admin
      kubernetes_version: "1.25.6"
      agent_count: 2
      aks_agent_vm_size: "Standard_D2_v2" # 8 core / 32GB
      zones:
        - "1"
        - "2"
        - "3"
    acr: 
      name: 
        - sampleappacr
      sku: "Standard"
    mssqlserver:
      name: dbserver-ue-primary
      dbs:
        db1:
          name: sampleappdb
          login: appuser
          user: appuser
          sku: GP_S_Gen5_2
        db2:
          name: sampleappdb2
          login: appuser
          user: appuser
          sku: GP_S_Gen5_2 
          sample_name: AdventureWorksLT         
      admin_login: sqladmin
      admin_password: *common_password
      dblogins:
        db1:
          name: appuser
          password: *common_password
      failover_group:
        name: "sampledb-failover-group"
    logicapp:
      name: sqlloginuserconnectorue
