projects:
  project1:
    name: gitops_project
    visibility: private
    agent_pool: Newlocal
    environments:
      env1:
        name: test-approval-check
    repos:
      repo1:
        name: terraform-code-repo
        init_type: Import
        imported_from: "https://github.com/harinderjits-git/gitops-azdevops.git" 
    variable_groups:
      vg1:
        name: vg1
        variables:
          variable4:
            name: ARM_CLIENT_ID
            equalto: yes
            is_secret: true
          variable5:
            name: ARM_CLIENT_SECRET
            equalto: yes
            is_secret: true
          variable6:
            name: ARM_TENANT_ID
            equalto: yes
            is_secret: true
          variable7:
            name: ARM_SUBSCRIPTION_ID
            equalto: yes
            is_secret: true
    pipelines:
      pipeline1:
        name: terraform-pipeline
        associated_repo: terraform-code-repo
        variable_group: vg1
        variables:
          variable1:
            name: local_state_file
            equalto: yes
            is_secret: false
          variable2:
            name: first_iteration
            equalto: yes
            is_secret: false
          variable3:
            name: terragrunt_action
            equalto: apply
            is_secret: false


#local_state_file, first_iteration, terragrunt_action, ARM_CLIENT_ID, ARM_CLIENT_SECRET, ARM_TENANT_ID, and ARM_SUBSCRIPTION_ID